import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js",
    template: "%s | Next.js",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1 style={{ backgroundColor: "lightblue", padding: "1rem" }}>
            Header
          </h1>
        </header>
        {children}
        <footer>
          <h1 style={{ backgroundColor: "salmon", padding: "1rem" }}>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
